// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8hzBCQ5MsTWyOC-SfxlwlakSMUhpqUnY',
    appId: '1:894750654398:web:4cc13d89d182a25b36c3ef',
    messagingSenderId: '894750654398',
    projectId: 'fleet-management-hackathon',
    authDomain: 'fleet-management-hackathon.firebaseapp.com',
    storageBucket: 'fleet-management-hackathon.firebasestorage.app',
    measurementId: 'G-NQKH3PE9QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxXhyOQfCbF3X4ngr0K22zFTdz4Lr8YjU',
    appId: '1:894750654398:android:0c272053070d830536c3ef',
    messagingSenderId: '894750654398',
    projectId: 'fleet-management-hackathon',
    storageBucket: 'fleet-management-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJyb_XIJku7uBEbTh3cZYc-7lZXNfesdU',
    appId: '1:894750654398:ios:ed8c3a71ce27827936c3ef',
    messagingSenderId: '894750654398',
    projectId: 'fleet-management-hackathon',
    storageBucket: 'fleet-management-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.fleetManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJyb_XIJku7uBEbTh3cZYc-7lZXNfesdU',
    appId: '1:894750654398:ios:ed8c3a71ce27827936c3ef',
    messagingSenderId: '894750654398',
    projectId: 'fleet-management-hackathon',
    storageBucket: 'fleet-management-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.fleetManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8hzBCQ5MsTWyOC-SfxlwlakSMUhpqUnY',
    appId: '1:894750654398:web:00c9395666d8dd1936c3ef',
    messagingSenderId: '894750654398',
    projectId: 'fleet-management-hackathon',
    authDomain: 'fleet-management-hackathon.firebaseapp.com',
    storageBucket: 'fleet-management-hackathon.firebasestorage.app',
    measurementId: 'G-QKD9WC05CV',
  );
}
